# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger: 
- none

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 
  buildConfiguratoin: 
  solution: '**/RoundTheCode.AzureTestProject.sln'
  project: '**/RoundTheCode.AzureTestProject.csproj'

steps:

- task: NuGetToolInstaller@1
  name: 'NuGetToolInstaller'
  displayName: 'NuGet tool installer'


- task: NuGetCommand@2
  name: 'NuGetRestore'
  displayName: 'NuGet restore packages'
  inputs:
        command: 'restore'
        restoreSolution: '$(solution)'
        feedsToUse: 'select'


- task: DotNetCoreCLI@2
  name: 'Tests'
  displayName: 'Run Tests'
  inputs:
        command: 'test'
        projects: '$(solution)'
        arguments: '--configuration '


- task: DotNetCoreCLI@2
  name: 'Publish'
  displayName: 'Publish'
  inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '$(project)'
        arguments: '--configuration --output $(Build.ArtifactStangingDirectory)'
        zipAfterPublish: false

- task: PublishBuildArtifacts@1
  name: 'PublishBuildArtifacts'
  displayName: 'Publish build artifacts'
  inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: 'AzureTestProject'
      publishLocation: 'Container'